server:
  port: 8090 # Port for the API Gateway

spring:
  application:
    name: spring-cloud-gateway
  cloud:
    gateway:
      routes:
        - id: customer
          uri: http://localhost:8081  # Service name registered in Eureka
          predicates:
            - Path=/api/v1/customers/**
          filters:
            - StripPrefix=1
        - id: fraud
          uri: http://localhost:8082  # Service name registered in Eureka
          predicates:
            - Path=/api/v1/fraud/**
          filters:
            - StripPrefix=1
        - id: products
          uri: http://localhost:8083  # Service name registered in Eureka
          predicates:
            - Path=/api/v1/products/**
          filters:
            - StripPrefix=1
        - id: authentication
          uri: http://localhost:8085  # Service name registered in Eureka
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - StripPrefix=1
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true