server:
  port: 8090 # Port for the API Gateway

spring:
  application:
    name: spring-cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
#      routes:
#        - id: customer
#          uri: lb://customer  # Service name registered in Eureka
#          predicates:
#            - Path=/api/v1/customers/**
#          filters:
#            - JwtFilter
#        - id: fraud
#          uri: lb://fraud  # Service name registered in Eureka
#          predicates:
#            - Path=/api/v1/fraud/**
#          filters:
#            - JwtFilter
#        - id: products
#          uri: lb://products  # Service name registered in Eureka
#          predicates:
#            - Path=/api/v1/products/**
#          filters:
#            - JwtFilter
#        - id: authentication
#          uri: lb://authentication  # Service name registered in Eureka
#          predicates:
#            - Path=/api/v1/auth/**
#          filters:
#            - JwtFilter

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
management:
  endpoints:
    web:
      exposure:
        include: gateway