spring:
  application:
    name: order
  datasource:
    url: jdbc:postgresql://localhost:5437/order
    password: 2001
    username: sergiu
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8086
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: localhost
management:
  tracing:
    sampling:
      probability: 1